#!/usr/bin/bash

PACKAGE="universal-chess"
DGTCM_PATH="/opt/${PACKAGE}"

function removePycache {    
    find ${DGTCM_PATH} | grep -E "(__pycache__|\.pyc|\.pyo$|epaper.jpg)" | xargs rm -rf
}


function stopServices {
    # Stop services in reverse dependency order
    # Use || true to prevent failures from aborting the upgrade
    systemctl stop universal-chess.service || true
    systemctl stop universal-chess-web.service || true
    systemctl stop universal-chess-stop-controller.service || true
    systemctl stop var-run-sdp.path || true
    systemctl stop var-run-sdp.service || true
    systemctl stop rfcomm.service || true
}


case $1 in
    remove* | upgrade )
        echo "::: Stopping services before $1..."
        stopServices || true
        removePycache
        exit 0
        ;;
esac
